### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading "length")

### ISSUE THREAD

**Issue by flamedfury** [chrisburnell/eleventy-cache-webmentions#5]
**Describe the bug**
Deploying to netlify:

```bash
10:20:10 PM: > cross-env ELEVENTY_ENV=production eleventy
10:20:11 PM: [flamedfury.com] Something went wrong with your request to webmention.io! TypeError: Cannot read properties of undefined (reading "length")
10:20:11 PM:     at /opt/build/repo/node_modules/@chrisburnell/eleventy-cache-webmentions/eleventy-cache-webmentions.js:108:28
10:20:11 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
10:20:11 PM:     at async fetchWebmentions (/opt/build/repo/node_modules/@chrisburnell/eleventy-cache-webmentions/eleventy-cache-webmentions.js:104:3)
10:20:11 PM:     at async filteredWebmentions (/opt/build/repo/node_modules/@chrisburnell/eleventy-cache-webmentions/eleventy-cache-webmentions.js:133:23)
10:20:11 PM:     at async filtered (/opt/build/repo/node_modules/@chrisburnell/eleventy-cache-webmentions/eleventy-cache-webmentions.js:238:32)
10:20:11 PM:     at async TemplateDataInitialGlobalData.getData (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateDataInitialGlobalData.js:24:25)
10:20:11 PM:     at async /opt/build/repo/node_modules/@11ty/eleventy/src/TemplateData.js:337:26
10:20:11 PM: [flamedfury.com] 0 filtered Webmentions pulled from cache.
```

**To Reproduce**

1. Go to https://github.com/flamedfury/flamedfury.com/commit/6876e3bd8d11a7a912981f0f5bcb48d14d66a46a
2. start deploy to netlify

**Environment:**

- Eleventy Version: 1.0.2
- 
**Additional context**
Builds and displays Webmentions locally, has issue when deploying to Netlify!

**Comment by chrisburnell** [comment]
Hey @flamedfury,

Thanks very much for the report and thanks for trying out my plugin! 😄

I think the issue here is coming from a slight differentiation in how the JSON and JF2 formats are returned from Webmention.io.

When making a request to `webmention.io/api/mentions.json`, the object key that holds the array of Webmentions is `links`.

On the flip side, when making a request to `webmention.io/api/mentions.jf2`, the object key that holds the array of Webmentions is `children`.

As you're requesting the JSON format, I think you’ll want to change the value of `key` in your config file from `children` to `links`. You can see the difference in the object structure between the two formats in your browser, using Postman, etc. I ought to make this distinction clear in my documentation/articles/etc.

Please do let me know if this doesn’t solve your immediate problem of being unable to successfully deploy with Webmentions being pulled in.

As for why it is working for you locally but not upon deploying to Netlify, I’m not immediately sure, but I will endeavour to do some testing and let you know if I come up with anything!

**Comment by flamedfury** [comment]
Thanks for taking a look @chrisburnell

Based on your reply I know what's happened. 

I originally followed the steps from https://chrisburnell.com/article/webmention-eleventy-setup/ that had `links` as the key.

This is why I was happily working while development.

Then I checked out the extra options over on https://chrisburnell.com/eleventy-cache-webmentions/#options that had `children` as the key.

I changed from `links` to `children` as I added some options before pushing my changes.

All working as expected now, just need to figure out what the post type for mastodon replies is...

**Comment by chrisburnell** [comment]
Hey @flamedfury, thanks for confirming that!

I'll amend the page on my website to be consistent about the `key` values I'm using; I appreciate you letting me know that's where the issue stemmed from.

As for Mastodon replies, that's the reason for my using the JF2 format returned by Webmention.io on my website: instead of having the value `null` for the `activity.type` key as the JSON format gives, it instead presents a `wm-property` key (with a value of `mention-of` for replies), which I feel affords me a bit more confidence in knowing what type of Webmention a given Webmention is.

Hopefully that helps! And remember to swap your `key` value back to `children` if you end up going down the same path as me and using the JF2 feed! 😬

**Comment by flamedfury** [comment]
Thanks @chrisburnell looks like I'm rocking now!

https://github.com/flamedfury/flamedfury.com/commit/cdfe9f74fcc9a7cdf34a8be844e0c25e653e1d11

https://flamedfury.com/posts/the-art-of-hyperlinking/
